# MySQL

- name: Configure MySQL Server
  hosts: db
  become: yes
  tasks:
    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Start MySQL Service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Check if root password is already set
      ansible.builtin.shell: "mysqladmin --user=root --password='' version"
      register: mysql_root_password
      ignore_errors: yes

    - name: Set MySQL root password if not already set
      ansible.builtin.shell: |
        mysqladmin -u root password "{{ mysql_root_password }}"
      when: mysql_root_password.rc != 0




        
   
