- name: Configure DB server
  hosts: db
  become: yes
  vars:
    login_host: "pragnadevops.online"
  vars_prompt:
  - name: mysql_root_password
    prompt: please enter password
    private: no 
  tasks:
    - name: Install MYSQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Start and enable MYSQL service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: setting up root password 
      ansible.builtin.command: "mysql_secure_installation --set-root-pass {{mysql_root_password}}"  #we using here prompt for password security.
      when: mysql_connection_output.failed is true #dont use {{}} in when 
