- name: Configure DB server
  hosts: db
  become: yes
  vars:
    login_host: "pragnadevops.online"
  tasks:
    - name: Install MYSQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Start and enable MYSQL service
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: Install dependency python packages.
      ansible.builtin.pip:
        name: 
        - PYMYSQL
        - cryptography #to use password
        executable: pip3.9  # we use pip3.11 if the phyton is using 3.11 version ,we can check by using ansible --version


    # Check if password is already set up or not
    - name: DB connection
      community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1
        login_host: "{{ login_host }}"
        filter: version
      ignore_errors: yes
      register: mysql_connection_output

    - name: Printing MySQL output
      ansible.builtin.debug:
        msg: "MySQL connection output is: {{ mysql_connection_output }}"
