- name: Configure DB server
  hosts: db
  become: yes
  tasks: 
   - name: Install MYSQL Server
     ansible.builtin.dnf:
      name: mysql-server
      state: latest
   - name: Start and enable service
     ansible.builtin.service:
       name: mysql
       state: started 
       enabled: yes
  #check password is already set up or not
  
   - name: check root password is exist or not
     community.mysql.mysql_info:
       login_user: root
       login_password: ExpenseApp@1
       filter: version

